DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND_ID INTEGER NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP DEFAULT NULL,
  PRICE_LIST INTEGER DEFAULT NULL,
  PRODUCT_ID INTEGER DEFAULT NULL,
  PRIORITY INTEGER DEFAULT NULL,
  PROD_PRICE FLOAT DEFAULT NULL,
  CURR VARCHAR(5) DEFAULT NULL
);